### ISSUE TITLE
Make extension instead of browser

### ISSUE THREAD

**Issue by filips123** [rllola/ZeronetBrowser#87]
### What?

I recommend that you make browser (at least for Firefox and Chrome) extension instead of the browser.

### Why?

* Many people don't want to have a separate browser just for ZeroNet
* This browser currently looks old and it misses a lot of features
* It will be easier for you to maintain extension instead of browser

### How?

You should make browser extension that would:

* Handle `zero:` links
* Offer development tools integrated into browser's dev tools
* Offer some GUI commands for ZeroNet management
* Integrate ZeroNet client directly into extenstion

Almost all of that things are possible with extension, only the last would be hard (but it is probably not so important).

There is already some project with extension:
* https://addons.mozilla.org/en-US/firefox/addon/zeronet-helper/
* https://github.com/krzysztof113/zeronet-helper

**Comment by rllola** [comment]
Hi

**Comment by filips123** [comment]
@rllola Why did you close this issue?

**Comment by rllola** [comment]
Hi @filips123,

Yes, sorry. The purpose of this project is to have a different browser for ZeroNet protocol for users to be more aware of what is being used. It means that what is happening in ZeroNet browser is part of ZeroNet. I agree not everyone might want 2 browsers and I have been looking into the extension. I would be happy to contribute to it.

I also think an application instead of an extension could offer more flexibility and shipping the browser with ZeroNet is the main idea behind this project.

I have close this issue because you are expressing an opinion and therefore it is not a bug/enhancement for this project. Feel free to contact me if you want to talk more about this.

**Comment by filips123** [comment]
Ok, I agree with that.

I also have one other suggestion.
Because maintaining browser would probably be hard and current browser misses a lot of features, you could maybe make a custom build of some browser (probably Firefox because it is more privacy oriented) and bundle ZeroNet and extension (for managing like in my first post) into it.
I don't know how exactly could this be done but you might consider this in the future.

**Comment by rllola** [comment]
Yeah I have been looking into that too. I wanted to do something like Tor browser did but it was easier for me to start from scratch. It is actually quite easy to do a browser in python using pyqt5 so I went with it. Also everything is in python than in firefox source code it seems to use rust, c++, some python script... I cant figure out what does what. Maybe if I had more experience in browser development but I am a total noob.

Also keep in mind this is a proof of concept and it is a good exercise. People can use it but I encourage people to try and contribute as it is fun but the browser comes with no warranty.

**Comment by filips123** [comment]
You could maybe do this in the future.

I also don't know how to integrate other programs into Firefox. But maybe there is some easy way to do this.

**Comment by filips123** [comment]
@rllola I created [Bugzilla suggestion](https://bugzilla.mozilla.org/show_bug.cgi?id=1549199) for support for creating custom Firefox bundles. I hope there will soon be some easy way to do this.
